### ISSUE TITLE
Looking for MultiQC report in the wrong place?

### ISSUE THREAD

**Issue by chrispyatt** [eastgenomics/eggd_artemis#22]
See job: https://platform.dnanexus.com/panx/projects/GgJ3gf04F80JY20Gjkp0QjF4/monitor/job/GjPykg84F80BB23Fx1gJ8Bgv

Logs contain the line below:
`No MultiQC report given, searching instead with path /output/CEN-240226_1342/dias_reports_v2.2.1_SNV/240417_1537`

But the MultiQC report isn't in the dias_reports directory. It's in `/output/CEN-240226_1342/eggd_MultiQC/`

**Comment by rklocke** [comment]
It only uses this path to find MultiQC reports which begin with the same single path, i.e. `/output/CEN-240226_1342`:
https://github.com/eastgenomics/eggd_artemis/blob/main/src/eggd_artemis.py#L421-L423

But the logs could definitely be clearer..
The issue for this job seems to be that the original MultiQC report in this project was deleted - which should also probably be fixed (though in the meantime giving the MultiQC report as an input will work)
